# Variables

In [1]:
a = 56

In [2]:
a

56

In [3]:
string1 = "Hello"

In [4]:
print(string1)

Hello


In [6]:
a = 5
b = 3
c = a
a = b
print("The new value of a is " , c , " b is " , a)

('The new value of a is ', 5, ' b is ', 3)


In [7]:
a, b = 3, 5
b, a = a, b

In [8]:
a

5

In [9]:
b

3

In [10]:
string1 = "Hello"

In [11]:
string1[0]

'H'

In [12]:
string1[0:3]

'Hel'

In [13]:
string1[:4]

'Hell'

In [14]:
string1[2:]

'llo'

In [15]:
len(string1)

5

In [16]:
string2 = "Howdy"

In [17]:
string2[-1]

'y'

In [18]:
a = '5'

In [19]:
b = "10"

In [20]:
c = '''34'''

In [23]:
b = int(a)

In [24]:
type(b)

int

In [25]:
string3 = "Nice to meet you"

In [26]:
string3[0:len(string3):2]

'Nc ome o'

In [27]:
string3[-1::-1]

'uoy teem ot eciN'

# Control Statements

In [28]:
if (b==32):
    print("False")
    print("Hi")
  print("hello")

IndentationError: unindent does not match any outer indentation level (<ipython-input-28-69cf6d9801df>, line 4)

In [29]:
a = 10

In [30]:
if (a==10):
    print("10 is found")

10 is found


In [36]:
if (a==20):
    print("a is not 20")
    
elif(a==10):
    print("a is 10")
else:
    print("a is something else")

a is 10


In [32]:
True and False

False

In [34]:
True or False

True

In [35]:
not True

False

# Iterative Statements

In [37]:
for i in range(10):     #equivalent of for(i=0; i<10; i++)
    print i

0
1
2
3
4
5
6
7
8
9


In [38]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
for i in range(40, 30, -1):
    print i

40
39
38
37
36
35
34
33
32
31


In [41]:
string1 = "Hello"

In [42]:
for i in string1:
    print i

H
e
l
l
o


In [46]:
if 'n' not in string1:
    print("n not found")

n not found


In [47]:
# data structures in python: tuples, dictionaries, list

In [48]:
'''
this 
is 
a multi-line comment
'''

'\nthis \nis \na multi-line comment\n'

In [49]:
list1 = ['hello', 'hi', 1, 2]

In [50]:
list1.append(10)

In [51]:
list1

['hello', 'hi', 1, 2, 10]

In [52]:
list1.insert(2, "Hello")

In [53]:
list1

['hello', 'hi', 'Hello', 1, 2, 10]

In [54]:
list1[2] = 'h'

In [55]:
string1 = "Howdy"

In [56]:
string1[0] = 'B'

TypeError: 'str' object does not support item assignment

In [57]:
a = "Hello " + " Howdy"

In [58]:
a

'Hello  Howdy'

In [59]:
list1.pop()

10

In [60]:
list1

['hello', 'hi', 'h', 1, 2]

In [61]:
del list1[0]

In [62]:
list1

['hi', 'h', 1, 2]

In [63]:
list1.remove("hi")

In [64]:
list1

['h', 1, 2]

In [65]:
list2=[1,2]

In [66]:
list1.append(list2)

In [67]:
list1

['h', 1, 2, [1, 2]]

In [69]:
list1+list2

['h', 1, 2, [1, 2], 1, 2]

In [70]:
list2

[1, 2]

In [71]:
list2.extend([1,3,4])

In [72]:
list2

[1, 2, 1, 3, 4]

In [73]:
list1[3][0]

1

In [74]:
list1 = [1, 2, 3, 4]

In [75]:
b = list1

In [76]:
b.append(5)

In [77]:
b

[1, 2, 3, 4, 5]

In [78]:
list1

[1, 2, 3, 4, 5]

In [79]:
tuple1 = (1, 2, 'hi')

In [80]:
tuple1[0] = 100

TypeError: 'tuple' object does not support item assignment

In [81]:
tuple1 + (5, 6)

(1, 2, 'hi', 5, 6)

In [82]:
tuple1.append(34)

AttributeError: 'tuple' object has no attribute 'append'

In [83]:
string1 = "hello" * 2

In [84]:
string1

'hellohello'

In [85]:
tuple1 * 2

(1, 2, 'hi', 1, 2, 'hi')

In [87]:
dict1 = {1:"Hello", 2: "Hi", 1: "Howdy"}

In [88]:
dict1

{1: 'Howdy', 2: 'Hi'}

In [89]:
dict1[1]

'Howdy'

In [124]:
dict1['me'] = "anon"

In [125]:
dict1

{1: 'Howdy', 2: 'Hi', 'me': 'anon'}

In [126]:
for k, v in dict1.iteritems():
    print k, v

me anon
1 Howdy
2 Hi


In [127]:
dict1.items()

[('me', 'anon'), (1, 'Howdy'), (2, 'Hi')]

In [95]:
a = set({1, 2, 3, 2, 5, 5, 6})

In [96]:
a

{1, 2, 3, 5, 6}

In [97]:
list1 = [2, 33, 5]

In [98]:
list1.sort()

In [99]:
list1

[2, 5, 33]

# Functions!

In [102]:
def func_name():          
    print("Hello World!")
    
func_name()

Hello World!


In [101]:
func_name()

Hello World!


In [103]:
def summation(a, b):
    return a+b

In [104]:
summation(3, 5)

8

In [105]:
def summa1 (a = 10, b = 2):
    return a+b

In [106]:
summa1()

12

In [107]:
summa1(2)

4

In [108]:
summa1(b=10)

20

In [109]:
summa1(22, 16)

38

In [110]:
summa1(b=20, a = 100)

120

In [123]:
def my_desc():
    my_name = "Anon"
    my_age = 21
    return my_name, my_age

name, age = my_desc()
print("Name: %s and Age: %d "%(name, age) )
print "name is ", name, 'and age is' , age

Name: Anon and Age: 21 
name is  Anon and age is 21


# NumPy!

In [130]:
import numpy as np

In [131]:
a = np.array([1, 2, 3])

In [132]:
a

array([1, 2, 3])

In [133]:
type(a)

numpy.ndarray

In [135]:
a.shape

(3,)

In [136]:
b = np.arange(10)

In [137]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
c = b.reshape(2,5)

In [142]:
c.shape

(2, 5)

In [143]:
c.ndim

2

In [144]:
c.dtype.name

'int64'

In [145]:
b = np.array([(1.5,2,3), (4,5,6)])

In [146]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [147]:
a = np.zeros( (3,4) )

In [148]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [149]:
a = np.ones((2,2))

In [150]:
a

array([[ 1.,  1.],
       [ 1.,  1.]])

In [151]:
a.dtype.name

'float64'

In [157]:
c = np.array( [ [1+5j,2], [3,4] ], dtype=complex )

In [158]:
c

array([[ 1.+5.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [154]:
np.empty( (2,3) )

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [155]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [156]:
np.linspace( 0, 2, 9 ) 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [159]:
c = np.arange(24).reshape(2,3,4)

In [160]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [161]:
a = np.array( [20,30,40,50] )

In [162]:
b = np.arange( 4 )

In [163]:
c = a - b

In [164]:
c

array([20, 29, 38, 47])

In [165]:
b ** 3

array([ 0,  1,  8, 27])

In [166]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [167]:
A = np.array( [[1,1],
             [0,1]] )

B = np.array( [[2,0],
          [3,4]] )

In [168]:
A*B

array([[2, 0],
       [0, 4]])

In [169]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [170]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [171]:
a = np.random.random((2,3))

In [172]:
a

array([[ 0.26348818,  0.56393498,  0.20981549],
       [ 0.3648135 ,  0.05164593,  0.8462371 ]])

In [173]:
a.sum()

2.2999351820231007

In [175]:
a.max()


0.84623710388500284

In [176]:
a.min()

0.051645930849234523

In [177]:
b = np.arange(12).reshape(3,4)

In [178]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [180]:
b.min(axis=1) 

array([0, 4, 8])

In [183]:
a = np.arange(10)**3

In [182]:
a[2]

8

In [184]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [185]:
a[:6:2] = -1000

In [186]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [189]:
b = np.random.random((5,4))

In [190]:
b

array([[ 0.92820182,  0.54611528,  0.6581277 ,  0.5857873 ],
       [ 0.96763761,  0.34529403,  0.11773227,  0.18202898],
       [ 0.86910776,  0.60050407,  0.25534905,  0.81057093],
       [ 0.02008839,  0.1761319 ,  0.28919816,  0.00911541],
       [ 0.33936569,  0.28731653,  0.29584239,  0.05095648]])

In [191]:
b[2,3]

0.81057092588487534

In [192]:
b[0:5, 1]   

array([ 0.54611528,  0.34529403,  0.60050407,  0.1761319 ,  0.28731653])

In [193]:
b[-1]  

array([ 0.33936569,  0.28731653,  0.29584239,  0.05095648])

In [194]:
a = np.floor(10*np.random.random((3,4)))

In [195]:
a

array([[ 6.,  5.,  1.,  8.],
       [ 4.,  2.,  2.,  4.],
       [ 6.,  1.,  7.,  5.]])

In [196]:
a.ravel()

array([ 6.,  5.,  1.,  8.,  4.,  2.,  2.,  4.,  6.,  1.,  7.,  5.])

In [199]:
a = a.reshape(6,2)

In [200]:
a.T

array([[ 6.,  1.,  4.,  2.,  6.,  7.],
       [ 5.,  8.,  2.,  4.,  1.,  5.]])

In [201]:
a

array([[ 6.,  5.],
       [ 1.,  8.],
       [ 4.,  2.],
       [ 2.,  4.],
       [ 6.,  1.],
       [ 7.,  5.]])

In [202]:
a = np.floor(10*np.random.random((2,2)))

In [203]:
b = np.floor(10*np.random.random((2,2)))

In [204]:
np.vstack((a,b))

array([[ 0.,  9.],
       [ 2.,  8.],
       [ 7.,  9.],
       [ 9.,  2.]])

In [205]:
np.hstack((a,b))

array([[ 0.,  9.,  7.,  9.],
       [ 2.,  8.,  9.,  2.]])

# Thanks!!!!